#!/bin/bash

#LINK DOMAIN
domain_name=x
ip_add=x.x.x.x

doctl compute domain records create --record-type A --record-name @ --record-data $ip_add $domain_name
doctl compute domain records create --record-type A --record-name www --record-data $ip_add $domain_name

#

read -p 'app_name:\t' app_name
read -p 'domain_name:\t' domain_name
web_root=/var/www
app_path=$web_root/$app_name

app_name_escaped=$(echo $app_name | sed "s|\/|\\\/|g")
domain_name_escaped=$(echo $domain_name | sed "s|\/|\\\/|g")
web_root_escaped=$(echo $web_root | sed "s|\/|\\\/|g")
app_path_escaped=$(echo $app_path | sed "s|\/|\\\/|g")

mkdir -p $web_root

if [ $app_name == "" ]; then
	echo "please give the application name as an argument"
	exit 0
fi

#UPDATE AND INSTALL ENVIRONMENT

yum -y update
yum -y install unzip
yum -y install vim
yum -y install epel-release

#DOWNLOAD WEB2PY


wget --output-document="$web_root/web2py_src.zip" http://www.web2py.com/examples/static/web2py_src.zip

cd $web_root
unzip web2py_src.zip
mv web2py $app_name
rm web2py_src.zip
cd $app_name

chmod -R  755 ${web_root}


#SETUP UWSGI
yum -y install epel-release
yum -y install python-devel python-pip gcc
pip install --upgrade pip
pip install uwsgi
cp $app_path/handlers/wsgihandler.py $app_path/
mkdir -p /etc/uwsgi/sites

echo "[uwsgi]
chdir = $app_path
module = wsgihandler:application

master = true
processes = 5

uid = root
socket = /run/uwsgi/${app_name}.sock
chown-socket = root:nginx
chmod-socket = 660
vacuum = true" > /etc/uwsgi/sites/${app_name}.ini

#openssl genrsa -out server.key 2048
#echo -e '\n\n\n\n\n\n\n\n\n' | openssl req -new -key server.key -out server.csr
#openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

#PREPARE SERVICE

echo "
[Unit]
Description=uWSGI Emperor Service

[Service]
ExecStartPre=-/usr/bin/bash -c 'mkdir -p /run/uwsgi; chown root:nginx /run/uwsgi'
ExecStart=/usr/bin/uwsgi --emperor /etc/uwsgi/sites
Restart=always
KillSignal=SIGQUIT
Type=notify
NotifyAccess=all

[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/uwsgi.service


#SETUP NGINX
yum -y install epel-release
yum -y install nginx
#tac /etc/nginx/nginx.conf | sed '0,/}/s/}/}\n\tserver_names_hash_bucket_size 64\n\tinclude \/etc\/nginx\/sites-enabled\/\*\.conf/' | tac > /etc/nginx/nginx.confTEMPORARY_FILE; mv /etc/nginx/nginx.confTEMPORARY_FILE /etc/nginx/nginx.conf
wget --output-document="/etc/nginx/nginx.conf" https://raw.githubusercontent.com/musicsmithnz/setup_scripts/master/nginx.conf.default
sed -i "s/APP_PATH/${app_path_escaped}/" /etc/nginx/nginx.conf
sed -i "s/APP_NAME/${app_name_escaped}/" /etc/nginx/nginx.conf
sed -i "s/DOMAIN_NAME/${domain_name_escaped}/" /etc/nginx/nginx.conf

mkdir -p /etc/nginx/sites-available
mkdir -p /etc/nginx/sites-enabled
wget --output-document="/etc/nginx/sites-available/${app_name}.conf" https://raw.githubusercontent.com/musicsmithnz/setup_scripts/master/nginx_sites_available.conf.default
sed -i "s/APP_NAME/${app_name_escaped}/" /etc/nginx/sites-available/${app_name}.conf
sed -i "s/DOMAIN_NAME/${domain_name_escaped}/" /etc/nginx/sites-available/${app_name}.conf
ln -s /etc/nginx/sites-available/${app_name}.conf /etc/nginx/sites-enabled/${app_name}.conf

echo "
routes_in = (
)

routes_out = [(x, y) for (y, x) in routes_in]

default_application = 'stylish_portfolio'
default_controller = 'main'
default_function = 'index'
" > $app_path/routes.py

systemctl start uwsgi.service;
systemctl enable uwsgi.service;
systemctl start nginx.service;
systemctl enable nginx.service;


#GENERATE SSL CERTIFICATE

domain_1=${domain_name}
domain_2=www.${domain_name}
yum -y install yum-utils
yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
yum -y install certbot
certbot certonly --standalone --preferred-challenges http -w $app_path -d $domain_1 -d $domain_2


#INFORM THE USER OF THE COMPLETION


IPADD=$(ip addr show eth0 | awk '{ print $2;}' | sed 's/\/.*$//' | grep -v '^[a-z]\|:\|^10\.\|^127\.\|^172\.\|^192\.168')
echo "you should be able to visit a new web2py server at: https://$IPADD";
