#!/bin/bash


keys=~/.ssh/digitalocean/keys

doctl compute droplet list; 
read -p "select id:" id;
ip=$(cat $keys | grep $id | cut -d'	' -f2);
path=$(cat $keys | grep $id | cut -d'	' -f3); 
#ssh -p 34533 root@$ip -i $path
ssh -p 22 root@$ip -i $path

echo path: $path
echo ip: $ip
echo id: $id
