#!/bin/bash

yum -y update
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
rpm -ivh epel-release-7-9.noarch.rpm

yum install python-pip
pip install --upgrade pip
pip install pyinotify
